import type { Car } from "./types"

export const dummyCars: Car[] = [
  {
    id: "1",
    make: "Toyota",
    model: "Corolla GLi",
    year: 2023,
    price: 4500000,
    mileage: 12000,
    city: "Karachi",
    condition: "used",
    engineSize: 1800,
    transmission: "automatic",
    fuelType: "petrol",
    images: ["/toyota-corolla-2023-front.jpg", "/toyota-corolla-interior.png", "/toyota-corolla-side.jpg"],
    description:
      "Well maintained Toyota Corolla GLi in excellent condition. Single owner, all service records available.",
    features: ["ABS", "Power Steering", "Air Conditioning", "Alloy Wheels", "Airbags"],
    seller: {
      name: "Ahmed Khan",
      phone: "+92 300 1234567",
      email: "ahmed@example.com",
    },
    postedDate: "2025-01-15",
    featured: true,
    picturesOnTheWay: false,
  },
  {
    id: "2",
    make: "Honda",
    model: "Civic Oriel",
    year: 2024,
    price: 7200000,
    mileage: 5000,
    city: "Lahore",
    condition: "used",
    engineSize: 1800,
    transmission: "automatic",
    fuelType: "petrol",
    images: ["/honda-civic-2024-white.jpg", "/honda-civic-interior-luxury.jpg", "/honda-civic-back.jpg"],
    description: "Like new Honda Civic Oriel with low mileage. Premium features and pristine condition.",
    features: ["Sunroof", "Leather Seats", "Navigation", "Reverse Camera", "Cruise Control"],
    seller: {
      name: "Fatima Ali",
      phone: "+92 321 7654321",
      email: "fatima@example.com",
    },
    postedDate: "2025-01-18",
    featured: true,
  },
  {
    id: "3",
    make: "Suzuki",
    model: "Alto VXR",
    year: 2022,
    price: 2300000,
    mileage: 25000,
    city: "Islamabad",
    condition: "used",
    engineSize: 660,
    transmission: "manual",
    fuelType: "petrol",
    images: ["/suzuki-alto-2022-red.jpg", "/suzuki-alto-interior.jpg", "/suzuki-alto-side.jpg"],
    description: "Economical Suzuki Alto in good condition. Perfect for city driving.",
    features: ["Power Windows", "Central Locking", "Air Conditioning"],
    seller: {
      name: "Usman Ahmed",
      phone: "+92 333 9876543",
      email: "usman@example.com",
    },
    postedDate: "2025-01-20",
  },
  {
    id: "4",
    make: "Mercedes",
    model: "C-Class C200",
    year: 2023,
    price: 14500000,
    mileage: 8000,
    city: "Karachi",
    condition: "used",
    engineSize: 2000,
    transmission: "automatic",
    fuelType: "petrol",
    images: [
      "/dummycar.jpg",
      "/dummycar.jpg",
      "/dummycar.jpg",
    ],
    description: "Luxury Mercedes C-Class with premium features. Immaculate condition.",
    features: ["Panoramic Sunroof", "Premium Sound System", "Adaptive Cruise", "LED Lights", "360 Camera"],
    seller: {
      name: "Saad Malik",
      phone: "+92 300 5551234",
      email: "saad@example.com",
    },
    postedDate: "2025-01-10",
    featured: true,
    picturesOnTheWay: true,
  },
  {
    id: "5",
    make: "BMW",
    model: "3 Series 320i",
    year: 2025,
    price: 16800000,
    mileage: 1500,
    city: "Lahore",
    condition: "new",
    engineSize: 2000,
    transmission: "automatic",
    fuelType: "petrol",
    images: [
      "/dummycar.jpg",
      "/dummycar.jpg",
      "/dummycar.jpg",
    ],
    description: "Brand new BMW 3 Series with latest technology and performance features.",
    features: ["iDrive System", "Wireless Charging", "Head-Up Display", "Park Assist", "Premium Audio"],
    seller: {
      name: "BMW Authorized Dealer",
      phone: "+92 321 1112222",
      email: "dealer@bmw.pk",
    },
    postedDate: "2025-01-22",
    featured: true,
     picturesOnTheWay: true,
  },
  {
    id: "6",
    make: "Audi",
    model: "A4 Sport",
    year: 2023,
    price: 13200000,
    mileage: 15000,
    city: "Islamabad",
    condition: "used",
    engineSize: 2000,
    transmission: "automatic",
    fuelType: "petrol",
    images: [
      "/dummycar.jpg",
      "/dummycar.jpg",
      "/dummycar.jpg",
    ],
    description: "Sporty Audi A4 with excellent performance. Well maintained with complete service history.",
    features: ["Virtual Cockpit", "Matrix LED", "Sport Suspension", "Bang & Olufsen Sound", "MMI Navigation"],
    seller: {
      name: "Zain Hassan",
      phone: "+92 333 7778888",
      email: "zain@example.com",
    },
    postedDate: "2025-01-12",
     picturesOnTheWay: true,
  },
]
